import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 22,
  tables: [
    // ===== MASTER DATA (pulled from server) =====
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'city_code', type: 'string', isOptional: true },
        { name: 'region_code', type: 'string', isOptional: true },
        { name: 'channel_code', type: 'string', isOptional: true },
        { name: 'customer_group', type: 'string', isOptional: true },
        { name: 'price_list', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'force_checkin_enabled', type: 'boolean', isOptional: true },
        { name: 'force_checkout_enabled', type: 'boolean', isOptional: true },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'items',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'brand', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'division', type: 'string', isOptional: true },
        { name: 'base_uom', type: 'string' },
        { name: 'tax_key', type: 'string', isOptional: true },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'prices',
      columns: [
        { name: 'server_id', type: 'number' },
        { name: 'item_code', type: 'string', isIndexed: true },
        { name: 'price_list', type: 'string', isIndexed: true },
        { name: 'region_code', type: 'string', isOptional: true, isIndexed: true },
        { name: 'price', type: 'number' },
        { name: 'mrp', type: 'number', isOptional: true },
        { name: 'set_price', type: 'number', isOptional: true },
        { name: 'currency_code', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'valid_from', type: 'string', isOptional: true },
        { name: 'valid_to', type: 'string', isOptional: true },
        { name: 'min_quantity', type: 'number', isOptional: true },
        { name: 'max_quantity', type: 'number', isOptional: true },
        { name: 'discount_percentage', type: 'number', isOptional: true },
        { name: 'promotional_price', type: 'number', isOptional: true },
        { name: 'server_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'journey_plan_customers',
      columns: [
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'route_code', type: 'string', isIndexed: true },
        { name: 'visit_day', type: 'string', isIndexed: true },
        { name: 'visit_sequence', type: 'number', isOptional: true },
        { name: 'frequency', type: 'string', isOptional: true },
      ],
    }),

    // ===== TRANSACTION DATA (created locally, pushed to server) =====
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'server_trx_code', type: 'string', isOptional: true },
        { name: 'user_code', type: 'string', isIndexed: true },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'customer_name', type: 'string', isOptional: true },
        { name: 'trx_date', type: 'number', isIndexed: true },
        { name: 'total_amount', type: 'number' },
        { name: 'lines_count', type: 'number' },
        { name: 'status', type: 'number' },
        { name: 'route_code', type: 'string', isOptional: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'order_lines',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'line_no', type: 'number' },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'quantity', type: 'number' },
        { name: 'price_used', type: 'number' },
        { name: 'tax_pct', type: 'number' },
        { name: 'uom', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'attendance_records',
      columns: [
        { name: 'user_code', type: 'string', isIndexed: true },
        { name: 'is_present', type: 'boolean' },
        { name: 'attendance_type', type: 'string', isOptional: true },
        { name: 'selfie_path', type: 'string', isOptional: true },
        { name: 'attendance_date', type: 'string', isIndexed: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'customer_visits',
      columns: [
        { name: 'visit_code', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string', isIndexed: true },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'customer_name', type: 'string', isOptional: true },
        { name: 'checkin_time', type: 'number', isIndexed: true },
        { name: 'checkout_time', type: 'number', isOptional: true },
        { name: 'checkin_lat', type: 'number', isOptional: true },
        { name: 'checkin_lng', type: 'number', isOptional: true },
        { name: 'checkin_image', type: 'string', isOptional: true },
        { name: 'checkout_lat', type: 'number', isOptional: true },
        { name: 'checkout_lng', type: 'number', isOptional: true },
        { name: 'checkout_image', type: 'string', isOptional: true },
        { name: 'duration_mins', type: 'number', isOptional: true },
        { name: 'checkin_type', type: 'string', isOptional: true },
        { name: 'checkout_type', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'store_checks',
      columns: [
        { name: 'app_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string', isIndexed: true },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'customer_name', type: 'string', isOptional: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'check_date', type: 'number', isIndexed: true },
        { name: 'total_count', type: 'number' },
        { name: 'food_count', type: 'number' },
        { name: 'non_food_count', type: 'number' },
        { name: 'status', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'store_check_items',
      columns: [
        { name: 'store_check_id', type: 'string', isIndexed: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string' },
        { name: 'category_name', type: 'string', isOptional: true },
        { name: 'brand_name', type: 'string', isOptional: true },
        { name: 'shelf_quantity', type: 'number' },
        { name: 'store_quantity', type: 'number' },
        { name: 'is_available', type: 'boolean' },
        { name: 'reason', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'planogram_executions',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'category_code', type: 'string', isOptional: true },
        { name: 'performed_on', type: 'number' },
        { name: 'is_followed', type: 'boolean' },
        { name: 'pre_image', type: 'string', isOptional: true },
        { name: 'post_image', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'approval_status', type: 'string', isOptional: true },
        { name: 'approved_by', type: 'string', isOptional: true },
        { name: 'approved_on', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'selling_skus',
      columns: [
        { name: 'item_code', type: 'string', isIndexed: true },
        { name: 'group_type', type: 'string', isOptional: true },
        { name: 'group_code', type: 'string', isIndexed: true },
        { name: 'is_core_sku', type: 'boolean' },
        { name: 'min_qty', type: 'number', isOptional: true },
        { name: 'max_qty', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'sync_meta',
      columns: [
        { name: 'module_name', type: 'string', isIndexed: true },
        { name: 'last_cursor', type: 'string', isOptional: true },
        { name: 'last_synced_at', type: 'number' },
      ],
    }),

    // ===== NEW v5 TABLES =====

    tableSchema({
      name: 'expiry_checks',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'quantity', type: 'number' },
        { name: 'uom', type: 'string' },
        { name: 'expiry_date', type: 'string' },
        { name: 'visited_date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'competitor_brands',
      columns: [
        { name: 'server_id', type: 'number' },
        { name: 'brand_code', type: 'string', isIndexed: true },
        { name: 'brand_name', type: 'string' },
        { name: 'company', type: 'string', isOptional: true },
        { name: 'category_code', type: 'string', isOptional: true },
        { name: 'category_name', type: 'string', isOptional: true },
        { name: 'competitor_brand_code', type: 'string', isOptional: true },
        { name: 'competitor_brand_name', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'competitor_observations',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'brand_name', type: 'string' },
        { name: 'product_name', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'price', type: 'number', isOptional: true },
        { name: 'selling_price', type: 'number', isOptional: true },
        { name: 'uom', type: 'string', isOptional: true },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'observed_on', type: 'number' },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'opening_stocks',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'brand', type: 'string', isOptional: true },
        { name: 'quantity', type: 'number' },
        { name: 'uom', type: 'string' },
        { name: 'stock_date', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'physical_stocks',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'brand', type: 'string', isOptional: true },
        { name: 'system_qty', type: 'number' },
        { name: 'physical_qty', type: 'number' },
        { name: 'uom', type: 'string' },
        { name: 'stock_date', type: 'string' },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'captured_on', type: 'number', isOptional: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'osoi_photos',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'asset_type', type: 'string' },
        { name: 'image_path', type: 'string' },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'captured_on', type: 'number' },
        { name: 'approval_status', type: 'string', isOptional: true },
        { name: 'approved_by', type: 'string', isOptional: true },
        { name: 'approved_on', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'po_captures',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'po_number', type: 'string' },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'total_amount', type: 'number' },
        { name: 'captured_on', type: 'number' },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'status', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'po_capture_items',
      columns: [
        { name: 'po_capture_id', type: 'string', isIndexed: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'quantity', type: 'number' },
        { name: 'price', type: 'number' },
        { name: 'uom', type: 'string' },
      ],
    }),

    // ===== NEW v6 TABLES =====

    tableSchema({
      name: 'initiatives',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'initiative_type', type: 'string' },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'target_channel', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'initiative_executions',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'initiative_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'executed_on', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'photo_path', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'product_samplings',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'item_code', type: 'string' },
        { name: 'item_name', type: 'string', isOptional: true },
        { name: 'quantity_sampled', type: 'number' },
        { name: 'uom', type: 'string' },
        { name: 'consumer_feedback', type: 'string', isOptional: true },
        { name: 'selling_price', type: 'number', isOptional: true },
        { name: 'units_sold', type: 'number', isOptional: true },
        { name: 'customers_approached', type: 'number', isOptional: true },
        { name: 'sampled_on', type: 'number' },
        { name: 'photo_path', type: 'string', isOptional: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'permanent_displays',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'display_type', type: 'string' },
        { name: 'location_description', type: 'string', isOptional: true },
        { name: 'standard_image_path', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'permanent_display_checks',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'display_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'is_compliant', type: 'boolean' },
        { name: 'issue_description', type: 'string', isOptional: true },
        { name: 'photo_path', type: 'string', isOptional: true },
        { name: 'checked_on', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'surveys',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'target_channel', type: 'string', isOptional: true },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'questions_json', type: 'string' },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'survey_responses',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'survey_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'visit_code', type: 'string', isOptional: true },
        { name: 'answers_json', type: 'string' },
        { name: 'completed_on', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'prospects',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_code', type: 'string' },
        { name: 'prospect_name', type: 'string' },
        { name: 'contact_name', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'channel_type', type: 'string', isOptional: true },
        { name: 'geo_lat', type: 'number', isOptional: true },
        { name: 'geo_lng', type: 'number', isOptional: true },
        { name: 'photo_path', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_on', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),

    // ===== NEW v7 TABLES =====
    tableSchema({
      name: 'collections',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'payment_mode', type: 'string' },
        { name: 'reference_number', type: 'string', isOptional: true },
        { name: 'collection_date', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'van_stock_records',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'item_code', type: 'string', isIndexed: true },
        { name: 'loaded_qty', type: 'number' },
        { name: 'sold_qty', type: 'number' },
        { name: 'balance_qty', type: 'number' },
        { name: 'stock_date', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'price_checks',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string' },
        { name: 'customer_code', type: 'string', isIndexed: true },
        { name: 'item_code', type: 'string' },
        { name: 'expected_price', type: 'number' },
        { name: 'actual_price', type: 'number' },
        { name: 'is_compliant', type: 'boolean' },
        { name: 'check_date', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'approval_records',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'request_type', type: 'string' },
        { name: 'reference_code', type: 'string', isOptional: true },
        { name: 'requester_code', type: 'string' },
        { name: 'approver_code', type: 'string', isOptional: true },
        { name: 'amount', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
      ],
    }),
    // Offline Rota drafts — written locally when the user creates a rota
    // with no network, pushed to /api/v1/rota on reconnect.
    tableSchema({
      name: 'rota_drafts',
      columns: [
        { name: 'app_trx_id', type: 'string', isIndexed: true },
        { name: 'user_code', type: 'string', isIndexed: true },
        { name: 'activity_name', type: 'string' },
        { name: 'rota_date', type: 'string', isIndexed: true },
        { name: 'start_time', type: 'string', isOptional: true },
        { name: 'end_time', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string' },
        { name: 'is_synced', type: 'boolean', isIndexed: true },
      ],
    }),
    // Planogram setups — pulled from web portal (Admin → Config → Planogram Setup)
    // so the mobile can show the recommended image + instructions offline.
    tableSchema({
      name: 'planogram_setups',
      columns: [
        { name: 'server_id', type: 'number', isIndexed: true },
        { name: 'selection_type', type: 'string', isIndexed: true },   // 'Customer' | 'SubChannel' | 'Region'
        { name: 'selection_value', type: 'string', isIndexed: true },  // e.g. 'DUMMYS2172'
        { name: 'category_code', type: 'string' },
        { name: 'category_name', type: 'string', isOptional: true },
        { name: 'asset_type', type: 'string', isOptional: true, isIndexed: true },
        { name: 'share_of_shelf_cm', type: 'number' },
        { name: 'suggested_image', type: 'string', isOptional: true },
        { name: 'instructions', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'server_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'app_settings',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
      ],
    }),
  ],
});
