# ─────────────────────────────────────────────────────────────
# VayAccess On-Site Agent — Target Installer (Portable Bundle)
#
# Runs on the gate PC AFTER you copied the portable bundle here.
# Prompts for the three env vars the agent needs, writes a .env
# file, and registers a Windows scheduled task that fires the
# bundled VayAccessAgent.exe on every system boot.
#
# USE:
#   Right-click PowerShell -> Run as Administrator
#   cd <folder-you-copied>
#   .\install.ps1
# ─────────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [string]$TaskName    = 'VayAccessOnSiteAgent',
    [string]$InstallDir  = $null
)

$ErrorActionPreference = 'Stop'

# --- 1. Elevation check -------------------------------------------------------
$principal = [Security.Principal.WindowsPrincipal]::new(
    [Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[ERR] Run this script as Administrator." -ForegroundColor Red
    Write-Host "     Right-click PowerShell -> 'Run as administrator', then run again."
    exit 1
}

# --- 2. Copy the bundle into a stable location so future upgrades are clean ---
if (-not $InstallDir) {
    $InstallDir = 'C:\Program Files\VayAccess'
}
$Source = $PSScriptRoot
$exe    = Join-Path $Source 'VayAccessAgent.exe'
if (-not (Test-Path $exe)) {
    Write-Host "[ERR] Bundle looks incomplete — VayAccessAgent.exe not found in $Source" -ForegroundColor Red
    Write-Host "     Make sure you're running install.ps1 from INSIDE the copied bundle folder."
    exit 1
}

Write-Host "[..] Installing bundle to $InstallDir ..." -ForegroundColor Cyan
if (Test-Path $InstallDir) {
    Write-Host "     (existing install found — stopping task + refreshing files)"
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Start-Sleep 2
    # Kill any running instance before overwrite.
    Get-Process VayAccessAgent -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep 1
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $InstallDir
}
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
# Copy everything from the bundle (skip install/uninstall scripts themselves).
Get-ChildItem $Source | Where-Object { $_.Name -notmatch '^(install|uninstall)\.ps1$' } |
    ForEach-Object { Copy-Item $_.FullName -Destination $InstallDir -Recurse -Force }

$InstalledExe = Join-Path $InstallDir 'VayAccessAgent.exe'
$InstalledEnv = Join-Path $InstallDir '.env'
$LogsDir      = Join-Path $InstallDir 'logs'
New-Item -ItemType Directory -Force -Path $LogsDir | Out-Null

# --- 3. Prompt for env vars ---------------------------------------------------
Write-Host ""
Write-Host "Enter configuration values. All are stored in $InstalledEnv." -ForegroundColor Cyan
Write-Host "(These values live only on this PC — never sent to chat or logs.)"
Write-Host ""

$dbUrl   = Read-Host "DATABASE_URL (Neon postgres connection string, e.g. postgresql://...)"
$pushUrl = Read-Host "CLOUD_PUSH_URL (default: https://vayaccess-cloud.onrender.com)"
if ([string]::IsNullOrWhiteSpace($pushUrl)) { $pushUrl = 'https://vayaccess-cloud.onrender.com' }
$pushTok = Read-Host "CLOUD_PUSH_TOKEN (the 64-char token from Render's env vars)" -AsSecureString

# Convert SecureString to plain text only long enough to write the .env file.
$pushTokPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($pushTok))

$camIp = Read-Host "Camera IP (default: 192.168.1.12) — press Enter to keep default"
if ([string]::IsNullOrWhiteSpace($camIp)) { $camIp = '192.168.1.12' }
$rfidIp = Read-Host "RFID reader IP (default: 192.168.0.200) — press Enter to keep default"
if ([string]::IsNullOrWhiteSpace($rfidIp)) { $rfidIp = '192.168.0.200' }

# --- 4. Write .env file ------------------------------------------------------
$envLines = @(
    "# Auto-generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    "# Do not commit this file to git."
    ""
    "DATABASE_URL=$dbUrl"
    "CLOUD_PUSH_URL=$pushUrl"
    "CLOUD_PUSH_TOKEN=$pushTokPlain"
    "CLOUD_MODE=0"
    "CLOUD_STREAM_FPS=10"
    "CLOUD_STREAM_JPEG_Q=60"
    "CAMERA_IP=$camIp"
    "RFID_READER_IP=$rfidIp"
)
$envLines | Set-Content -Encoding utf8 -Path $InstalledEnv

# Wipe the plain-text password from memory as fast as we can.
$pushTokPlain = $null
[GC]::Collect()

# --- 5. Register scheduled task ----------------------------------------------
Write-Host "[..] Registering scheduled task '$TaskName' (runs on boot as SYSTEM)..." -ForegroundColor Cyan
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction `
    -Execute        $InstalledExe `
    -WorkingDirectory $InstallDir

$trigger = New-ScheduledTaskTrigger -AtStartup
$trigger.Delay = 'PT30S'

$principalT = New-ScheduledTaskPrincipal `
    -UserId    'NT AUTHORITY\SYSTEM' `
    -LogonType ServiceAccount `
    -RunLevel  Highest

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Days 999) `
    -MultipleInstances IgnoreNew

Register-ScheduledTask `
    -TaskName    $TaskName `
    -Description "VayAccess on-site agent — polls UHF reader, decodes RTSP, pushes scans + frames to cloud. Auto-starts on system boot." `
    -Action      $action `
    -Trigger     $trigger `
    -Principal   $principalT `
    -Settings    $settings | Out-Null

Write-Host "[OK] Scheduled task '$TaskName' registered." -ForegroundColor Green

# --- 6. Start it right away so the operator can verify without a reboot ------
Write-Host "[..] Starting agent now to verify install..." -ForegroundColor Cyan
Start-ScheduledTask -TaskName $TaskName
Start-Sleep 5
$state = (Get-ScheduledTask -TaskName $TaskName).State

Write-Host ""
Write-Host "======================================================================"
Write-Host "  Install complete." -ForegroundColor Green
Write-Host "======================================================================"
Write-Host "  Install path:  $InstallDir"
Write-Host "  Task state:    $state"
Write-Host "  Log directory: $LogsDir"
Write-Host ""
Write-Host "  Verify by watching the log:"
Write-Host "    Get-Content '$LogsDir\*.log' -Wait -Tail 20"
Write-Host ""
Write-Host "  Uninstall:"
Write-Host "    cd '$InstallDir'"
Write-Host "    .\uninstall.ps1"
Write-Host "======================================================================"
